In [2]:
import pandas as pd

In [6]:
print(pd.__version__)

3.0.6

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [25]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [11]:
df.shape[0]

10000

In [16]:
df["fuel_type"].unique().tolist()

['Gasoline', 'Diesel', 'Hybrid']

In [27]:
df.isna().any().sum()

np.int64(2)

In [22]:
df["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [31]:
df["horsepower"].median()

np.float64(252.0)

In [28]:
df["horsepower"].mode()[0]

np.float64(252.0)

In [29]:
df["horsepower"] = df["horsepower"].fillna(252.0)

In [30]:
df["horsepower"].median()

np.float64(252.0)

In [32]:
asian_cars_df = df[df["origin"] == "Asia"]

In [33]:
asian_cars_df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [34]:
asian_cars_filtered_column_df = df.loc[df["origin"] == "Asia", ["vehicle_weight", "model_year"]]

In [36]:
asian_cars_filtered_column_df.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [41]:
X = asian_cars_filtered_column_df.head(7).to_numpy()
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [43]:
import numpy as np
XTX = np.matmul(X.T, X)
XTX.shape
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

In [46]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv.shape
print(XTX_inv)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [47]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [48]:
z= np.matmul(XTX_inv,X.T)
print(z)

[[-2.50082897e-04 -1.65786806e-05 -2.86196661e-04  3.99964853e-04
  -1.18162927e-03  1.10298508e-03  2.25354894e-04]
 [ 6.12974614e-04  1.06954785e-04  6.91249245e-04 -7.95968736e-04
   2.63152339e-03 -2.31749941e-03 -4.16221392e-04]]

In [49]:
w = np.matmul(z,y)
print(w)

[0.13644777 0.2327492 ]

In [50]:
w.sum()

np.float64(0.36919696904925486)